import nextConfig from "eslint-config-next";
import nextCoreWebVitalsConfig from "eslint-config-next/core-web-vitals";
import nextTypescriptConfig from "eslint-config-next/typescript";

const config = [
  ...nextConfig,
  ...nextCoreWebVitalsConfig,
  ...nextTypescriptConfig,
  {
    ignores: [
      "node_modules/**",
      ".next/**",
      "out/**",
      "build/**",
      "next-env.d.ts",
      // AI-DLC harness runtimes generated by `aidlc config`
      ".agents/skills/**",
      ".aidlc/**",
      ".claude/**",
      ".codex/**",
      ".cursor/**",
      ".kiro/**",
      ".opencode/**",
    ],
  },
];

export default config;
